### ISSUE TITLE
Consider simplifying information modeling via YAML

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/dps#7]
There is a discussion during meetings and on the mailing list if information modeling should be introduced employing a special language like JADN to separate information level models from format spoecific data models.

But, the contributed JSON Schema (currently the only information readily available to the TC) is very simple in its use of types.

Short naive analysis ignoreing the location of elements:

```bash
❯ grep type dp-x.json | tr -s " " | tr -d '",' | cut -f2 -d: | sort | uniq -c | sort -nr
  46  string
  21  array
  18  object
   1  boolean
```

There is currently a single bool property, 46 occurences of string properties and quite some sequential and mapping containers.

So, essentially we model hierarchical strings thaat are placed inside a tree of potentially infinite depth.

I understand from this preliminary screening analysis, that we should be able to use YAML snippets inside the prose to define the information we are after and esp. the relationships between the nearly all text-only snippets in instances. YAML is much more readable for humans then e.g. JSON and is able to nicely expose relationships.

This way we would not need to introduce UML types and then rely on outside generators to derive the specific schema files in the needed formats (like CBOR, JSON, XML, YAML, or others), so less effort for editors and maintainers alike.

**Comment by kpodnar-dta** [comment]
For the immediate next steps, I support using YAML to define relationships and structure within the spec.

**Comment by davaya** [comment]
The purpose of an information model is to discuss and define requirements for document contents in the way one would do on a whiteboard.  JADN is one such notation, but ignoring JADN entirely, the text:
```
Metadata = Record                                // The Data Provenance Standard Metadata
   1 source           Source                     // Describes a dataset and the source of the dataset.
   2 provenance       Provenance                 // Provenance of the dataset.
   3 use              Use                        // Legal use and restrictions.

Provenance = Record
   1 source           URL [1..*]                 // Source metadata for dataset
   2 origin           Org optional               // Source
   3 origin-geography geo:Country-Name [1..*]    // Data origin geography
   4 date             Timestamp                  // Dataset issue date
   5 previous-date    Timestamp                  // Date of previously-issued version of the dataset
   6 generation-period Generation                // Range of dates for data generation
   7 generation-method Method [1..*]             // Method (code/system/description?)
   8 format           MediaType [0..*]           // Data format
   9 sub-provenance   Provenance                 // Add key/link?

  . . .
```
is a succinct way of both discussing data requirements and defining them in the DPS specification separately from data formats.  

YAML and JSON Schema are both format-specific, but more significantly, they are more verbose and far less readable than an abstract specification. The YAML specification is currently 272 lines long, starting with:
```
properties:
  provenance:
    description: This describes the provenance of the dataset.
    properties:
      date: {description: 'The date when the dataset was compiled or created, providing
          a temporal context for the data.', type: string}
      format:
        description: Describes the nature of the data within the dataset, such as
          numerical, textual, or multimedia, helping users understand what kind of
          information is contained within the file or dataset.
        items: {type: string}
        minItems: 0
        type: array
        uniqueItems: true
      generation-method:
        description: The methodology or procedures used to collect, generate, or compile
          the data, giving insight into its reliability and validity.
      . . .
```
The DPS text specification is 72 lines long.  The DPS TC can stop there and do nothing other than publish the "whiteboard design" text.

But the text also happens to be in a format defined by an OASIS specification, and it is defined in such a way that it can be automatically translated into multiple data formats including JSON, YAML and XML, and implemented in applications such as the Metadata Generator.
